version: "3.7"
services:
  belajar-docker:
    image: nginx
    volumes:
    - .:/usr/share/nginx/html:ro
     - nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "3333:80"
    environment:
    - VIRTUAL_HOST=example.awek
    - NGINX_PORT=80