version: "3.7"
services:
  belajar-docker:
    image: nginx
    volumes:
    - ./page/index.html:/usr/share/nginx/html
    ports:
    - "3333:80"
    environment:
    - NGINX_HOST=spotlution.localhost
    - NGINX_PORT=80