version: "3.7"
services:
  belajar-docker:
    image: nginx
    volumes:
    - .:/usr/share/nginx/html:ro
    ports:
    - "3333:80"
    environment:
    - NGINX_HOST=spotlution.localhost
    - NGINX_PORT=80