version: "3.7"
services:
  belajar-docker:
    image: nginx
    volumes:
    - ./page:/etc/nginx/templates
    ports:
    - "3333:80"
    environment:
    - NGINX_HOST=spotlution.localhost
    - NGINX_PORT=80