version: "3.7"
services:
  belajar-docker:
    image: nginx
    volumes:
    - .:/usr/share/nginx/html:ro
    - ./nginx.conf:/etc/nginx/conf.d/tes.conf:ro
    ports:
    - "3333:1234"
    environment:
    - VIRTUAL_HOST=example.localhost
    - NGINX_PORT=1234